name: Build FF Marlin

on:
  push:
    branches:
    - fork-main
    - release/*
    
jobs:
  build:
     strategy:
       matrix:
          machine: [dreamer-nx,dreamer,inventor]
          
     runs-on: ubuntu-latest
     steps:
     - name: Install platformio 
       run: echo "Hello ${{ github.event.inputs.name }}"
     - name: Building ${{ matrix.machine }}
       run:  echo "Hello ${{ matrix.machine }}"
