name: Build FF Marlin

on:
  push:
    branches:
    - fork-main
    - release/*
    
jobs:
  build:
     strategy:
       matrix:
          machine: [dreamer-nx,dreamer,inventor]
          
     runs-on: ubuntu-latest
     steps:
     - name: Install platformio 
       run: |
         python3 -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"
         export PATH=$PATH:~/.platformio/penv/bin
         platformio --version
     - name: Building ${{ matrix.machine }}
       run:  echo "Hello ${{ matrix.machine }}"
