name: Build FF Marlin

on:
  push:
    branches:
    - fork-main
    - release/*
    
jobs:
  build:
     strategy:
       matrix:
          machine: [dreamer-nx,dreamer,inventor]
          
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
      - name: Check out repository
        uses: actions/checkout@v2         
      - name: Building ${{ matrix.machine }}
        run:  |
         platformio --version
         ./build_marlin.sh ${{ matrix.machine }}
